### PR TITLE
Vendor WinMD files

### PR DESCRIPTION
**Pull request by paulcbetts**
Instead of relying on whatever happens to be on the user's computer, we'll check in a specific version of the WinMD files (the FCU version) and point the build to this. Without this PR, I couldn't get the project to build at all.

### CODE REVIEW

**Comment by patriksvensson** [comment]
@paulcbetts Thanks! I completely overlooked this.
Is it OK to redistribute those files btw?

**Comment by patriksvensson** [comment]
@paulcbetts Thanks for this PR, really appreciated!

**Comment by paulcbetts** [comment]
@patriksvensson Probably! It's just definitions, there are no code.

**Comment by patriksvensson** [comment]
@paulcbetts Yes, I figured the same and went ahead and merged this.

**Pull request merged**
